import axios, { AxiosInstance } from 'axios';
import { LLMProvider } from './base-provider.js';

export class CopilotProvider implements LLMProvider {
  name = 'Copilot';
  private apiKey: string;
  private modelName: string;
  private httpClient: AxiosInstance;

  constructor(
    apiKey: string,
    model: string = 'gpt-4o',
    httpClient: AxiosInstance = axios
  ) {
    this.apiKey = apiKey;
    this.modelName = model;
    this.httpClient = httpClient;
  }

  async sendMessage(prompt: string): Promise<string> {
    try {
      const response = await this.httpClient.post(
        'https://api.github.com/copilot/chat/completions',
        {
          messages: [
            {
              role: 'user',
              content: prompt,
            },
          ],
          model: this.modelName,
          temperature: 0.7,
          max_tokens: 2048,
        },
        {
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${this.apiKey}`,
            'Accept': 'application/vnd.github.copilot+json',
            'Editor-Version': 'vscode/1.85.0',
          },
        }
      );

      if (response.data.choices && response.data.choices.length > 0) {
        return response.data.choices[0].message.content;
      } else {
        throw new Error('No content generated by Copilot');
      }
    } catch (error: any) {
      if (axios.isAxiosError(error)) {
        throw new Error(`Copilot API error: ${error.response?.data?.error?.message || error.message}`);
      }
      throw error;
    }
  }

  async analyzeImage(imagePath: string, prompt: string = 'Describe this image concisely'): Promise<string> {
    try {
      // Read image and convert to base64
      const fs = await import('fs/promises');
      const imageBuffer = await fs.readFile(imagePath);
      const base64Image = imageBuffer.toString('base64');

      // Determine image format
      const ext = imagePath.split('.').pop()?.toLowerCase() || 'jpg';
      const mimeType = ext === 'png' ? 'image/png' : 'image/jpeg';

      const response = await this.httpClient.post(
        'https://api.github.com/copilot/chat/completions',
        {
          messages: [
            {
              role: 'user',
              content: [
                {
                  type: 'text',
                  text: prompt,
                },
                {
                  type: 'image_url',
                  image_url: {
                    url: `data:${mimeType};base64,${base64Image}`,
                  },
                },
              ],
            },
          ],
          model: this.modelName,
          temperature: 0.7,
          max_tokens: 2048,
        },
        {
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${this.apiKey}`,
            'Accept': 'application/vnd.github.copilot+json',
            'Editor-Version': 'vscode/1.85.0',
          },
        }
      );

      if (response.data.choices && response.data.choices.length > 0) {
        return response.data.choices[0].message.content;
      } else {
        throw new Error('No content generated by Copilot for image analysis');
      }
    } catch (error: any) {
      if (axios.isAxiosError(error)) {
        throw new Error(`Copilot vision API error: ${error.response?.data?.error?.message || error.message}`);
      }
      throw error;
    }
  }

  async isAvailable(): Promise<boolean> {
    try {
      const response = await this.httpClient.get('https://api.github.com/copilot/models', {
        headers: {
          'Authorization': `Bearer ${this.apiKey}`,
          'Accept': 'application/vnd.github.copilot+json',
        },
      });
      return response.status === 200;
    } catch {
      return false;
    }
  }
}
